/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as OrganizationsNewRouteImport } from './routes/organizations.new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as OrgIdProjectsRouteImport } from './routes/$orgId.projects'
import { Route as OrgIdProjectsNewRouteImport } from './routes/$orgId.projects.new'
import { Route as ProjectProjectIdWorkbenchRouteImport } from './routes/project.$projectId.workbench'
import { Route as ProjectProjectIdTmRouteImport } from './routes/project.$projectId.tm'
import { Route as ProjectProjectIdSettingsRouteImport } from './routes/project.$projectId.settings'
import { Route as ProjectProjectIdMembersRouteImport } from './routes/project.$projectId.members'
import { Route as ProjectProjectIdJobsRouteImport } from './routes/project.$projectId.jobs'
import { Route as ProjectProjectIdHistoryRouteImport } from './routes/project.$projectId.history'
import { Route as ProjectProjectIdGlossaryRouteImport } from './routes/project.$projectId.glossary'
import { Route as ProjectProjectIdDocumentsRouteImport } from './routes/project.$projectId.documents'
import { Route as ProjectProjectIdDashboardRouteImport } from './routes/project.$projectId.dashboard'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIdProjectsRoute = OrgIdProjectsRouteImport.update({
  id: '/$orgId/projects',
  path: '/$orgId/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIdProjectsNewRoute = OrgIdProjectsNewRouteImport.update({
  id: '/$orgId/projects/new',
  path: '/$orgId/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdWorkbenchRoute =
  ProjectProjectIdWorkbenchRouteImport.update({
    id: '/workbench',
    path: '/workbench',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdTmRoute = ProjectProjectIdTmRouteImport.update({
  id: '/tm',
  path: '/tm',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdSettingsRoute =
  ProjectProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdMembersRoute = ProjectProjectIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdJobsRoute = ProjectProjectIdJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdHistoryRoute = ProjectProjectIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdGlossaryRoute =
  ProjectProjectIdGlossaryRouteImport.update({
    id: '/glossary',
    path: '/glossary',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdDocumentsRoute =
  ProjectProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdDashboardRoute =
  ProjectProjectIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings': typeof SettingsRoute
  '/$orgId/projects': typeof OrgIdProjectsRoute
  '/$orgId/projects/new': typeof OrgIdProjectsNewRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/dashboard': typeof ProjectProjectIdDashboardRoute
  '/project/$projectId/documents': typeof ProjectProjectIdDocumentsRoute
  '/project/$projectId/glossary': typeof ProjectProjectIdGlossaryRoute
  '/project/$projectId/history': typeof ProjectProjectIdHistoryRoute
  '/project/$projectId/jobs': typeof ProjectProjectIdJobsRoute
  '/project/$projectId/members': typeof ProjectProjectIdMembersRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId/tm': typeof ProjectProjectIdTmRoute
  '/project/$projectId/workbench': typeof ProjectProjectIdWorkbenchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings': typeof SettingsRoute
  '/$orgId/projects': typeof OrgIdProjectsRoute
  '/$orgId/projects/new': typeof OrgIdProjectsNewRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/dashboard': typeof ProjectProjectIdDashboardRoute
  '/project/$projectId/documents': typeof ProjectProjectIdDocumentsRoute
  '/project/$projectId/glossary': typeof ProjectProjectIdGlossaryRoute
  '/project/$projectId/history': typeof ProjectProjectIdHistoryRoute
  '/project/$projectId/jobs': typeof ProjectProjectIdJobsRoute
  '/project/$projectId/members': typeof ProjectProjectIdMembersRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId/tm': typeof ProjectProjectIdTmRoute
  '/project/$projectId/workbench': typeof ProjectProjectIdWorkbenchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings': typeof SettingsRoute
  '/$orgId/projects': typeof OrgIdProjectsRoute
  '/$orgId/projects/new': typeof OrgIdProjectsNewRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/dashboard': typeof ProjectProjectIdDashboardRoute
  '/project/$projectId/documents': typeof ProjectProjectIdDocumentsRoute
  '/project/$projectId/glossary': typeof ProjectProjectIdGlossaryRoute
  '/project/$projectId/history': typeof ProjectProjectIdHistoryRoute
  '/project/$projectId/jobs': typeof ProjectProjectIdJobsRoute
  '/project/$projectId/members': typeof ProjectProjectIdMembersRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId/tm': typeof ProjectProjectIdTmRoute
  '/project/$projectId/workbench': typeof ProjectProjectIdWorkbenchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/organizations'
    | '/organizations/new'
    | '/settings'
    | '/$orgId/projects'
    | '/$orgId/projects/new'
    | '/project/$projectId'
    | '/project/$projectId/dashboard'
    | '/project/$projectId/documents'
    | '/project/$projectId/glossary'
    | '/project/$projectId/history'
    | '/project/$projectId/jobs'
    | '/project/$projectId/members'
    | '/project/$projectId/settings'
    | '/project/$projectId/tm'
    | '/project/$projectId/workbench'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/organizations'
    | '/organizations/new'
    | '/settings'
    | '/$orgId/projects'
    | '/$orgId/projects/new'
    | '/project/$projectId'
    | '/project/$projectId/dashboard'
    | '/project/$projectId/documents'
    | '/project/$projectId/glossary'
    | '/project/$projectId/history'
    | '/project/$projectId/jobs'
    | '/project/$projectId/members'
    | '/project/$projectId/settings'
    | '/project/$projectId/tm'
    | '/project/$projectId/workbench'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/organizations'
    | '/organizations/new'
    | '/settings'
    | '/$orgId/projects'
    | '/$orgId/projects/new'
    | '/project/$projectId'
    | '/project/$projectId/dashboard'
    | '/project/$projectId/documents'
    | '/project/$projectId/glossary'
    | '/project/$projectId/history'
    | '/project/$projectId/jobs'
    | '/project/$projectId/members'
    | '/project/$projectId/settings'
    | '/project/$projectId/tm'
    | '/project/$projectId/workbench'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  SettingsRoute: typeof SettingsRoute
  OrgIdProjectsRoute: typeof OrgIdProjectsRoute
  OrgIdProjectsNewRoute: typeof OrgIdProjectsNewRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgId/projects': {
      id: '/$orgId/projects'
      path: '/$orgId/projects'
      fullPath: '/$orgId/projects'
      preLoaderRoute: typeof OrgIdProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgId/projects/new': {
      id: '/$orgId/projects/new'
      path: '/$orgId/projects/new'
      fullPath: '/$orgId/projects/new'
      preLoaderRoute: typeof OrgIdProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/workbench': {
      id: '/project/$projectId/workbench'
      path: '/workbench'
      fullPath: '/project/$projectId/workbench'
      preLoaderRoute: typeof ProjectProjectIdWorkbenchRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/tm': {
      id: '/project/$projectId/tm'
      path: '/tm'
      fullPath: '/project/$projectId/tm'
      preLoaderRoute: typeof ProjectProjectIdTmRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings': {
      id: '/project/$projectId/settings'
      path: '/settings'
      fullPath: '/project/$projectId/settings'
      preLoaderRoute: typeof ProjectProjectIdSettingsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/members': {
      id: '/project/$projectId/members'
      path: '/members'
      fullPath: '/project/$projectId/members'
      preLoaderRoute: typeof ProjectProjectIdMembersRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/jobs': {
      id: '/project/$projectId/jobs'
      path: '/jobs'
      fullPath: '/project/$projectId/jobs'
      preLoaderRoute: typeof ProjectProjectIdJobsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/history': {
      id: '/project/$projectId/history'
      path: '/history'
      fullPath: '/project/$projectId/history'
      preLoaderRoute: typeof ProjectProjectIdHistoryRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/glossary': {
      id: '/project/$projectId/glossary'
      path: '/glossary'
      fullPath: '/project/$projectId/glossary'
      preLoaderRoute: typeof ProjectProjectIdGlossaryRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/documents': {
      id: '/project/$projectId/documents'
      path: '/documents'
      fullPath: '/project/$projectId/documents'
      preLoaderRoute: typeof ProjectProjectIdDocumentsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/dashboard': {
      id: '/project/$projectId/dashboard'
      path: '/dashboard'
      fullPath: '/project/$projectId/dashboard'
      preLoaderRoute: typeof ProjectProjectIdDashboardRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdDashboardRoute: typeof ProjectProjectIdDashboardRoute
  ProjectProjectIdDocumentsRoute: typeof ProjectProjectIdDocumentsRoute
  ProjectProjectIdGlossaryRoute: typeof ProjectProjectIdGlossaryRoute
  ProjectProjectIdHistoryRoute: typeof ProjectProjectIdHistoryRoute
  ProjectProjectIdJobsRoute: typeof ProjectProjectIdJobsRoute
  ProjectProjectIdMembersRoute: typeof ProjectProjectIdMembersRoute
  ProjectProjectIdSettingsRoute: typeof ProjectProjectIdSettingsRoute
  ProjectProjectIdTmRoute: typeof ProjectProjectIdTmRoute
  ProjectProjectIdWorkbenchRoute: typeof ProjectProjectIdWorkbenchRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdDashboardRoute: ProjectProjectIdDashboardRoute,
  ProjectProjectIdDocumentsRoute: ProjectProjectIdDocumentsRoute,
  ProjectProjectIdGlossaryRoute: ProjectProjectIdGlossaryRoute,
  ProjectProjectIdHistoryRoute: ProjectProjectIdHistoryRoute,
  ProjectProjectIdJobsRoute: ProjectProjectIdJobsRoute,
  ProjectProjectIdMembersRoute: ProjectProjectIdMembersRoute,
  ProjectProjectIdSettingsRoute: ProjectProjectIdSettingsRoute,
  ProjectProjectIdTmRoute: ProjectProjectIdTmRoute,
  ProjectProjectIdWorkbenchRoute: ProjectProjectIdWorkbenchRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  SettingsRoute: SettingsRoute,
  OrgIdProjectsRoute: OrgIdProjectsRoute,
  OrgIdProjectsNewRoute: OrgIdProjectsNewRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
